AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-data-sculptor

  Sample SAM Template for sam-data-sculptor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  API:
    Type: AWS::Serverless::Api # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: MyLambdaAuthorizer
        Authorizers:
          MyLambdaAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_api/
      Handler: create.lambda_handler
      Runtime: python3.12
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref API
            Path: /user
            Method: POST
            Auth:
              Authorizer: NONE

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_api/
      Handler: update.lambda_handler
      Runtime: python3.12
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
      - x86_64
      Events:
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /user/{userId}
            Method: PATCH
            Auth:
              Authorizer: MyLambdaAuthorizer

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_api/
      Handler: deleteUser.lambda_handler
      Runtime: python3.12
      Timeout: 5
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
      - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /user/{userId}
            Method: DELETE
            Auth:
              Authorizer: MyLambdaAuthorizer

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer/
      Handler: login.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
      - x86_64
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /login
            Method: POST
            Auth:
              Authorizer: NONE

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer/
      Handler: basic.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures: 
      - x86_64

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: user_id
        Type: String
      TableName: ds_users
